# Generated by Django 3.0.7 on 2020-08-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddrInfo',
            fields=[
                ('bdmgtsn', models.CharField(db_column='bdMgtSn', max_length=25, primary_key=True, serialize=False)),
                ('udrtyn', models.CharField(blank=True, db_column='udrtYn', max_length=1, null=True)),
                ('buldmnnm', models.IntegerField(blank=True, db_column='buldMnnm', null=True)),
                ('buldslno', models.IntegerField(blank=True, db_column='buldSlno', null=True)),
                ('areano', models.CharField(blank=True, db_column='areaNo', max_length=5, null=True)),
                ('chgrsncd', models.CharField(blank=True, db_column='chgRsnCd', max_length=2, null=True)),
                ('ntcdate', models.CharField(blank=True, db_column='ntcDate', max_length=8, null=True)),
                ('stnmbfr', models.CharField(blank=True, db_column='stNmBfr', max_length=25, null=True)),
                ('addrstus', models.CharField(blank=True, db_column='addrStus', max_length=1, null=True)),
            ],
            options={
                'db_table': 'addr_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddrRoad',
            fields=[
                ('rnmgtsn', models.CharField(db_column='rnMgtSn', max_length=12, primary_key=True, serialize=False)),
                ('rn', models.CharField(blank=True, db_column='rn', max_length=80, null=True)),
                ('rneng', models.CharField(blank=True, db_column='rnEng', max_length=80, null=True)),
                ('emdno', models.CharField(db_column='emdNo', max_length=2)),
                ('sinm', models.CharField(blank=True, db_column='siNm', max_length=20, null=True)),
                ('sinmeng', models.CharField(blank=True, db_column='siNmEng', max_length=40, null=True)),
                ('sggnm', models.CharField(blank=True, db_column='sggNm', max_length=20, null=True)),
                ('sggnmeng', models.CharField(blank=True, db_column='sggNmEng', max_length=40, null=True)),
                ('emdnm', models.CharField(blank=True, db_column='emdNm', max_length=20, null=True)),
                ('emdnmeng', models.CharField(blank=True, db_column='emdNmEng', max_length=40, null=True)),
                ('emddiv', models.CharField(blank=True, db_column='emdDiv', max_length=1, null=True)),
                ('emdcd', models.CharField(blank=True, db_column='emdCd', max_length=3, null=True)),
                ('usage', models.CharField(blank=True, max_length=1, null=True)),
                ('chgrsn', models.CharField(blank=True, db_column='chgRsn', max_length=1, null=True)),
                ('chginfo', models.CharField(blank=True, db_column='chgInfo', max_length=14, null=True)),
                ('ntcdate', models.CharField(blank=True, db_column='ntcDate', max_length=8, null=True)),
                ('expdate', models.CharField(blank=True, db_column='expDate', max_length=8, null=True)),
            ],
            options={
                'db_table': 'addr_road',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrTitleInfo',
            fields=[
                ('platplc', models.CharField(db_column='platPlc', max_length=200)),
                ('sigungucd', models.CharField(db_column='sigunguCd', max_length=5)),
                ('bjdongcd', models.CharField(db_column='bjdongCd', max_length=5)),
                ('bun', models.CharField(db_column='bun', max_length=4)),
                ('ji', models.CharField(db_column='ji', max_length=4)),
                ('mgmbldrgstpk', models.CharField(db_column='mgmBldrgstPk', max_length=33, primary_key=True, serialize=False)),
                ('archarea', models.CharField(blank=True, db_column='archArea', max_length=45, null=True)),
                ('grndflrcnt', models.IntegerField(blank=True, db_column='grndFlrCnt', null=True)),
            ],
            options={
                'db_table': 'br_title_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddrAddinfo',
            fields=[
                ('bdmgtsn', models.OneToOneField(db_column='bdMgtSn', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='address.AddrInfo')),
                ('hjdongcd', models.CharField(blank=True, db_column='hjdongCd', max_length=10, null=True)),
                ('hjdongnm', models.CharField(blank=True, db_column='hjdongNm', max_length=20, null=True)),
                ('zipno', models.CharField(blank=True, db_column='zipNo', max_length=5, null=True)),
                ('zipsrlno', models.CharField(blank=True, db_column='zipSrlNo', max_length=3, null=True)),
                ('lrgdlvry', models.CharField(blank=True, db_column='lrgDlvry', max_length=40, null=True)),
                ('bdrgstrbdnm', models.CharField(blank=True, db_column='bdRgstrBdNm', max_length=40, null=True)),
                ('sggbdnm', models.CharField(blank=True, db_column='sggBdNm', max_length=40, null=True)),
                ('bdkdcd', models.CharField(blank=True, db_column='bdKdcd', max_length=1, null=True)),
            ],
            options={
                'db_table': 'addr_addinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddrJibun',
            fields=[
                ('bdmgtsn', models.ForeignKey(db_column='bdMgtSn', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='address.AddrInfo')),
                ('srlno', models.IntegerField(db_column='srlNo')),
                ('dongcd', models.CharField(blank=True, db_column='dongCd', max_length=10, null=True)),
                ('sinm', models.CharField(blank=True, db_column='siNm', max_length=20, null=True)),
                ('sggnm', models.CharField(blank=True, db_column='sggNm', max_length=20, null=True)),
                ('emdnm', models.CharField(blank=True, db_column='emdNm', max_length=20, null=True)),
                ('linm', models.CharField(blank=True, db_column='liNm', max_length=20, null=True)),
                ('mtyn', models.CharField(blank=True, db_column='mtYn', max_length=1, null=True)),
                ('lnbrmnnm', models.IntegerField(blank=True, db_column='lnbrMnnm', null=True)),
                ('lnbrslno', models.IntegerField(blank=True, db_column='lnbrSlno', null=True)),
                ('repyn', models.CharField(blank=True, db_column='repYn', max_length=1, null=True)),
            ],
            options={
                'db_table': 'addr_jibun',
                'managed': False,
            },
        ),
    ]
