# Generated by Django 3.0.7 on 2020-08-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addraddinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='addrjibun',
            options={'managed': True},
        ),
    ]
