# Generated by Django 3.0.7 on 2020-08-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200824_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsEmd',
            fields=[
                ('emdcd', models.IntegerField(db_column='emdCd', primary_key=True, serialize=False)),
                ('sggcd', models.IntegerField(db_column='sggCd')),
                ('emdnm', models.CharField(db_column='emdNm', max_length=20)),
                ('emdnmeng', models.CharField(db_column='emdNmEng', max_length=40)),
            ],
            options={
                'db_table': 'units_emd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitsRoad',
            fields=[
                ('roadcd', models.IntegerField(db_column='roadCd', primary_key=True, serialize=False)),
                ('sggcd', models.IntegerField(db_column='sggCd')),
                ('roadnm', models.CharField(db_column='roadNm', max_length=20)),
                ('roadnmeng', models.CharField(db_column='roadNmEng', max_length=40)),
            ],
            options={
                'db_table': 'units_road',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitsSgg',
            fields=[
                ('sggcd', models.IntegerField(db_column='sggCd', primary_key=True, serialize=False)),
                ('sidocd', models.IntegerField(db_column='sidoCd')),
                ('sggnm', models.CharField(db_column='sggNm', max_length=20)),
                ('sggnmeng', models.CharField(db_column='sggNmEng', max_length=40)),
            ],
            options={
                'db_table': 'units_sgg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitsSido',
            fields=[
                ('sidocd', models.IntegerField(db_column='sidoCd', primary_key=True, serialize=False)),
                ('sinm', models.CharField(db_column='siNm', max_length=20)),
                ('sinmeng', models.CharField(db_column='siNmEng', max_length=40)),
                ('treeord', models.IntegerField(blank=True, db_column='treeOrd', null=True)),
            ],
            options={
                'db_table': 'units_sido',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='addrjibun',
            name='bdmgtsn',
            field=models.OneToOneField(db_column='bdMgtSn', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='address.AddrInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='addrjibun',
            unique_together={('bdmgtsn', 'srlno')},
        ),
    ]
