# Generated by Django 3.0.7 on 2020-09-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200831_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.CharField(db_column='id', max_length=12, primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
    ]
