# Generated by Django 3.0.7 on 2020-09-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtors',
            fields=[
                ('reg_dt', models.DateTimeField(blank=True, null=True)),
                ('mng_no', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('biz_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('biz_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('rep_name', models.CharField(max_length=50)),
                ('rep_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_raw', models.CharField(blank=True, max_length=200, null=True)),
                ('temp', models.CharField(blank=True, max_length=5, null=True)),
                ('sinm', models.CharField(blank=True, db_column='siNm', max_length=20, null=True)),
                ('sggnm', models.CharField(blank=True, db_column='sggNm', max_length=20, null=True)),
                ('rn', models.CharField(blank=True, max_length=80, null=True)),
                ('udrtyn', models.CharField(blank=True, db_column='udrtYn', max_length=1, null=True)),
                ('buldmnnm', models.IntegerField(blank=True, db_column='buldMnnm', null=True)),
                ('buldslno', models.IntegerField(blank=True, db_column='buldSlno', null=True)),
                ('emdnm', models.CharField(blank=True, db_column='emdNm', max_length=20, null=True)),
                ('linm', models.CharField(blank=True, db_column='liNm', max_length=20, null=True)),
                ('mtyn', models.CharField(blank=True, db_column='mtYn', max_length=1, null=True)),
                ('lnbrmnnm', models.IntegerField(blank=True, db_column='lnbrMnnm', null=True)),
                ('lnbrslno', models.IntegerField(blank=True, db_column='lnbrSlno', null=True)),
                ('addr_etc', models.CharField(blank=True, max_length=40, null=True)),
                ('addr_rn', models.CharField(blank=True, max_length=200, null=True)),
                ('addr_jibun', models.CharField(blank=True, max_length=200, null=True)),
                ('bdmgtsn', models.CharField(blank=True, db_column='bdMgtSn', max_length=25, null=True)),
                ('srlno', models.CharField(blank=True, db_column='srlNo', max_length=3, null=True)),
                ('rnmgtsn', models.CharField(blank=True, db_column='rnMgtSn', max_length=12, null=True)),
                ('emdno', models.CharField(blank=True, db_column='emdNo', max_length=2, null=True)),
            ],
            options={
                'db_table': 'realtors',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UnitsEmd',
        ),
        migrations.DeleteModel(
            name='UnitsRoad',
        ),
        migrations.DeleteModel(
            name='UnitsSgg',
        ),
        migrations.DeleteModel(
            name='UnitsSido',
        ),
        migrations.AlterModelTable(
            name='units',
            table='addr_units',
        ),
    ]
